CREATE DATABASE IF NOT EXISTS db;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT ALL PRIVILEGES ON db.* TO 'user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;